version: '2'
services:
    cards-app:
        image: cards
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mariadb://cards-mariadb:3306/cards
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=cards-elasticsearch:9300
    cards-mariadb:
        extends:
            file: mariadb.yml
            service: cards-mariadb
    cards-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: cards-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
